AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
  DisplayCopNames: true
  TargetRubyVersion: 3.1

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 16
Metrics/ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded
